### ISSUE TITLE
[VUE] When jumping from one comment area to another, the comments on the previous page are still displayed

### ISSUE THREAD

**Issue by aiktb** [giscus/giscus-component#1370]
### How to reproduce:

Enter the following webpage, after the comments are loaded, click "Next Page" in the lower right corner to observe the comments.
https://strapi-community.github.io/strapi-plugin-rest-cache/guide/#frontmatter-title

### Display

![Snipaste_2023-04-23_22-02-31](https://user-images.githubusercontent.com/104723527/233844282-026aae2d-a970-4bc4-9ef6-fc71b64e2e14.png)
![Snipaste_2023-04-23_22-02-50](https://user-images.githubusercontent.com/104723527/233844294-706fbf1b-bd95-44e5-ac76-32c9bb501adf.png)

**Comment by laymonage** [comment]
This is just due to how Vue works and how your website is set up.

https://github.com/strapi-community/strapi-plugin-rest-cache/blob/main/docs/.vitepress/theme/Layout.vue

When you switch to a different page, none of the attributes of the giscus component changes, and Vue tries to be smart by reusing the component, as it thinks the component has not changed.

You need to either use a `key` attribute with a value that changes when you navigate to a different page, or use other ways to ensure that the component gets re-rendered when the page changes.

https://vuejs.org/api/built-in-special-attributes.html#key

**Comment by aiktb** [comment]
通过`:key`已解决
