### ISSUE TITLE
mode prop

### ISSUE THREAD

**Issue by yowainwright** [giscus/giscus-component#49]
## Feature Request

1. Thanks for Giscus and making this super clean component API! 💪 
2. I would love to have access to a "mode" prop (or similar)

I was just trying to create a custom theme so I could seamlessly incorporate giscus—as it is AWESOME! 🙏 
I have implemented dark and light modes for the site in which I use Giscus. 

1. Can we add a "mode" prop?
2. But first, do you already recommend a happy path for adding dark and light modes with custom themes? 🤔 

---

## Current Solution

Currently I pass in `isDarkMode` context and toggle the Giscuss theme based on that:

```js
export default function SomeComp() {
  const { isDarkMode } = useContext(GlobalState);
  const theme = isDarkMode ? 'dark' : 'light';
  return (
        <div className='post__giscus'>
          <Giscus
            {...propsNotRelevantToQuestion }
            theme={theme}
          />
        </div>
  )
}
```

## Desired Solution

Mode context is added to the iframe so I can style like so:

```css
/* mytheme.css */
.some-css-class {
  color: #000;
}
[mode=dark] .some-css-class {
  color: #fff;
}
```

```js
export default function SomeComp() {
  const { isDarkMode } = useContext(GlobalState);
  const mode = isDarkMode ? 'dark' : 'light';
  return (
        <div className='post__giscus'>
          <Giscus
           {...propsNotRelevantToQuestion }
            mode={mode}
            theme='mytheme.css'
          />
        </div>
  )
}
```

Happy to learn rather than add an uneeded feature if I'm missing something in my understanding! 🙏

**Comment by laymonage** [comment]
Couldn't you have two CSS files and change the `theme` value to point to the correct file based on `mode`?

**Comment by yowainwright** [comment]
@laymonage thanks for your hasty response! 

Yes! But I'd prefer to leverage the CSS cascade vs making/managing unneeded requests and `.css` files. 

Happy to leave the conversation at that, though. 

The API is super clean so I trust in the architect. 🙏

**Comment by laymonage** [comment]
Ah, I understand.

> The API is super clean so I trust in the architect! 🙏

Thanks, but honestly this would've been so much easier had I introduced the custom CSS support using a different config (e.g. `themeUrl` instead of using the same `theme` for both built-in and custom themes). That way, you could've specified one `themeUrl` with different `theme` values (like the `mode` prop you described here) and used the `[data-theme="mycustomtheme"]` CSS selector ([ref](https://github.com/giscus/giscus/blob/main/pages/widget.tsx#L146)) to use the appropriate styles. Right now the `data-theme` attribute just resolves to `custom` if you're using a custom theme, which isn't very useful.

Changing this now would break existing users with custom themes. Though, I did add a warning that the custom CSS support is experimental, so it's to be expected.

Another option would be to add a new prop like you suggest here, but I'm not convinced it's worth adding yet. If I ever decide to do so, I'll let you know =)

**Comment by yowainwright** [comment]
That makes 💯  sense to me! Thanks for keeping the api clean ✨
